name: havadurumu
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #Network
  http: ^0.13.4
  dio: ^4.0.6

  #State Management
  mobx: ^2.0.7+3
  flutter_mobx: ^2.0.6+1
  mobx_codegen: ^2.0.7
  build_runner: ^2.1.11

  #Assets
  flutter_launcher_icons_maker: ^0.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true
  macos: true
  windows: true
  web: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/